### ISSUE TITLE
code?

### ISSUE THREAD

**Issue by uzleosharif** [tum-ei-eda/TinyML-Examples#1]
hi the idea for this repo looks really interesting for newbies like me to get their hands dirty with tinyml stuff. Unfortunately I couldn't find any working code in a quick browse of repo. Is this active? or else has this moved to some new location?

**Comment by PhilippvK** [comment]
If you are interested in TinyML code target at STM32 hardware, have a look at https://github.com/tum-ei-eda/stm32-tflm-demos. Three famous models should be implemented there. They have not been updated since November so you will probably need to use an older Tensorflow version.

**Comment by uzleosharif** [comment]
cool many thanks..I have a look there
